/*
 * $Id: ForeachHandler.java,v 1.9 2005/05/04 05:05:58 spal Exp $
 * $Source: /cvsroot/sqlunit/sqlunit/src/net/sourceforge/sqlunit/handlers/ForeachHandler.java,v $
 * SQLUnit - a test harness for unit testing database stored procedures.
 * Copyright (C) 2003  The SQLUnit Team
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package net.sourceforge.sqlunit.handlers;

import net.sourceforge.sqlunit.HandlerFactory;
import net.sourceforge.sqlunit.IErrorCodes;
import net.sourceforge.sqlunit.IHandler;
import net.sourceforge.sqlunit.SQLUnitException;
import net.sourceforge.sqlunit.SymbolTable;
import net.sourceforge.sqlunit.utils.TypeUtils;
import net.sourceforge.sqlunit.utils.XMLUtils;

import org.apache.log4j.Logger;
import org.jdom.Element;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 * This class implements the handling of the foreach element. The foreach
 * element is used to specify loops in the setup, prepare and teardown
 * elements.
 * @author Sujit Pal (spal@users.sourceforge.net)
 * @version $Revision: 1.9 $
 * @sqlunit.parent name="setup" ref="setup"
 * @sqlunit.parent name="prepare" ref="prepare"
 * @sqlunit.parent name="teardown" ref="teardown"
 * @sqlunit.element name="foreach"
 *  description="The foreach tag allows for simple bulk substitution by 
 *  replacing a named parameter in a SQL statement with values from a 
 *  supplied list or values generated by incrementing a counter. The
 *  syntax is similar to FOR and FOREACH statements found in most 
 *  programming languages."
 *  syntax="((sql)*)"
 * @sqlunit.attrib name="param"
 *  description="The name of the parameter that will be substituted in the
 *  SQL statement. For example, if the param is id, then all occurences of
 *  ${id} will be substituted by the current value of id."
 *  required="Yes"
 * @sqlunit.attrib name="values"
 *  description="A comma-separated list of values for the id. A value set
 *  can be specified within each element in the list. The elements of the 
 *  set are separated with semi-colons. They are referred to later in the
 *  scope of the foreach tag as value_of_param.index. The index is 0-based."
 *  required="No, either this or (start,stop,(step)) or (start,count,(step))
 *  may be specified"
 * @sqlunit.attrib name="start"
 *  description="Specifies the starting value of the sequence of values
 *  for the param"
 *  required="No, values can be specified instead. If neither is specified,
 *  then start defaults to 0."
 * @sqlunit.attrib name="stop"
 *  description="The ending value of the sequence of values for param"
 *  required="No, count can be specified instead."
 * @sqlunit.attrib name="step"
 *  description="The increment if a sequence is specified with start and stop"
 *  required="No, defaults to 1."
 * @sqlunit.attrib name="count"
 *  description="The number of entries in the sequence specified by start
 *  and stop."
 *  required="No, stop can be specified instead."
 * @sqlunit.child name="sql"
 *  description="Contains a single SQL statement with placeholders for param
 *  which will be executed in a loop specified by the foreach attributes. The
 *  replaceable placeholder(s) should be specified as ${id}."
 *  required="Yes"
 *  ref="sql"
 * @sqlunit.example name="A foreach used to prepare test data"
 *  description="
 *  <prepare>{\n}
 *  {\t}<sql><stmt>delete from foreachtest where 1=1</stmt></sql>{\n}
 *  {\t}<foreach param=\"id\" start=\"0\" stop=\"10\" step=\"1\">{\n}
 *  {\t}{\t}<sql>
 *  {\t}{\t}{\t}<stmt>insert into foreachtest (id,name) values (${id},'name${id}')</stmt>{\n}
 *  {\t}{\t}</sql>{\n}
 *  {\t}</foreach>{\n}
 *  </prepare>{\n}
 *  "
 */
public class ForeachHandler implements IHandler {

    private static final Logger LOG = Logger.getLogger(ForeachHandler.class);

    /**
     * Processes the content of the foreach element, returns a null.
     * @param elForeach the foreach element to parse.
     * @return a null object.
     * @throws Exception if one is thrown by the underlying methods.
     */
    public final Object process(final Element elForeach) throws Exception {
        LOG.debug(">> process(elForeach)");
        if (elForeach == null) {
            throw new SQLUnitException(IErrorCodes.ELEMENT_IS_NULL,
                new String[] {"foreach"});
        }
        String param = XMLUtils.getAttributeValue(elForeach, "param");
        String values = XMLUtils.getAttributeValue(elForeach, "values");
        boolean isListForm = (values != null);
        List valuesList = new ArrayList();
        // build the list of values for our replaceable parameter
        if (!isListForm) {
            String start = XMLUtils.getAttributeValue(elForeach, "start");
            String stop = XMLUtils.getAttributeValue(elForeach, "stop");
            String step = XMLUtils.getAttributeValue(elForeach, "step");
            String count = XMLUtils.getAttributeValue(elForeach, "count");
            // we can have (start,stop|count,(interval))
            if (start == null) {
                throw new SQLUnitException(IErrorCodes.ELEMENT_IS_NULL,
                    new String[] {"foreach@start"});
            }
            boolean isCountForm = false;
            if (stop == null && count == null) {
                return null;
            } else {
                isCountForm = (count != null);
            }
            int startIndex = TypeUtils.convertStringToInt(start, 0);
            int stepIndex = TypeUtils.convertStringToInt(step, 1);
            int stopIndex = 0;
            if (isCountForm) {
                int countInt = TypeUtils.convertStringToInt(count, 0);
                stopIndex = startIndex + ((countInt - 1) * stepIndex);
            } else {
                stopIndex = TypeUtils.convertStringToInt(stop, startIndex);
            }
            for (int i = startIndex; i <= stopIndex; i += stepIndex) {
                valuesList.add((new Integer(i)).toString());
            }
        } else {
            String[] tokens = values.split("\\s*,\\s*");
            for (int i = 0; i < tokens.length; i++) {
                String[] subtokens;
                if (tokens[i].indexOf(';') > -1) {
                    // if we have semi-colon separated strings, build array
                    // and stuff into the valuesList
                    subtokens = tokens[i].split("\\s*;\\s*");
                    valuesList.add(subtokens);
                } else {
                    // else stuff a string
                    valuesList.add(tokens[i].trim());
                }
            }
        }
        // get list of sql tags and pass to the SqlHandler
        IHandler handler = HandlerFactory.getInstance("sql");
        List elSqlList = elForeach.getChildren("sql");
        Iterator elSqlIter = elSqlList.iterator();
        while (elSqlIter.hasNext()) {
            Element elSql = (Element) elSqlIter.next();
            String sql = XMLUtils.getText(elSql.getChild("stmt"));
            int numQueries = valuesList.size();
            for (int sqlIndex = 0; sqlIndex < numQueries; sqlIndex++) {
                String sqlToRun = sql;
                // save the param (array) into the symbol table
                Object valueObj = valuesList.get(sqlIndex);
                if (valueObj instanceof String[]) {
                    String[] valueArray = (String[]) valueObj;
                    for (int i = 0; i < valueArray.length; i++) {
                        SymbolTable.setValue("${" + param + "." + i + "}",
                            valueArray[i]);
                        sqlToRun = sqlToRun.replaceAll(
                            "\\$\\{" + param + "." + i + "\\}",
                            valueArray[i].trim());
                    }
                } else {
                    SymbolTable.setValue("${" + param + "}", 
                        (String) valuesList.get(sqlIndex));
                    sqlToRun = sql.replaceAll("\\$\\{" + param + "\\}", 
                        (String) valuesList.get(sqlIndex));
                }
                elSql.getChild("stmt").setText(sqlToRun);
                // delegate to the sql handler
                handler.process(elSql);
                // remove the param (array) from the symbol table
                if (valueObj instanceof String[]) {
                    String[] valueArray = (String[]) valueObj;
                    for (int i = 0; i < valueArray.length; i++) {
                        SymbolTable.removeSymbol("${" + param + "." + i + "}");
                    }
                } else {
                    SymbolTable.removeSymbol("${" + param + "}");
                }
            }
        }
        // return null
        return null;
    }
}
