/* Generated By:JavaCC: Do not edit this line. IncludeFileParserConstants.java */
package net.sourceforge.sqlunit.parsers;

public interface IncludeFileParserConstants {

  int EOF = 0;
  int DEFAULT_WHITESPACE = 1;
  int LEADING_DELIMITER = 2;
  int TRAILING_DELIMITER = 3;
  int START_SINGLELINE_COMMENT = 4;
  int START_MULTILINE_COMMENT = 5;
  int START_MULTILINE = 6;
  int START_EXEC_PROC_CALL = 7;
  int START_EXEC_PROC_OTHER = 8;
  int START_SHELL_CALL = 9;
  int START_OTHER_SQL_CHAR = 10;
  int END_SINGLELINE_COMMENT = 11;
  int SINGLELINE_COMMENT_CHAR = 12;
  int END_MULTILINE_COMMENT = 13;
  int MULTILINE_COMMENT_CHAR = 14;
  int MULTILINE_DELIMITER = 15;
  int MULTILINE_CHAR = 16;
  int EXEC_PROC_CONT_CHAR = 17;
  int EXEC_PROC_OPEN_PAREN = 18;
  int EXEC_PROC_CLOSE_PAREN = 19;
  int EXEC_PROC_DELIMITER = 20;
  int EXEC_PROC_CHAR = 21;
  int SHELL_CONT_CHAR = 22;
  int SHELL_CALL_DELIMITER = 23;
  int OPEN_PAREN = 24;
  int CLOSE_PAREN = 25;
  int SHELL_CALL_CHAR = 26;
  int OTHER_SQL_DELIMITER = 27;
  int OTHER_SQL_CHAR = 28;

  int DEFAULT = 0;
  int IN_SINGLELINE_COMMENT = 1;
  int IN_MULTILINE_COMMENT = 2;
  int IN_MULTILINE_CALL = 3;
  int IN_EXEC_PROC = 4;
  int IN_SHELL_CALL = 5;
  int IN_OTHER_SQL = 6;

  String[] tokenImage = {
    "<EOF>",
    "<DEFAULT_WHITESPACE>",
    "<LEADING_DELIMITER>",
    "<TRAILING_DELIMITER>",
    "\"--\"",
    "\"/*\"",
    "<START_MULTILINE>",
    "\"{CALL \"",
    "<START_EXEC_PROC_OTHER>",
    "\"!\"",
    "<START_OTHER_SQL_CHAR>",
    "<END_SINGLELINE_COMMENT>",
    "<SINGLELINE_COMMENT_CHAR>",
    "<END_MULTILINE_COMMENT>",
    "<MULTILINE_COMMENT_CHAR>",
    "<MULTILINE_DELIMITER>",
    "<MULTILINE_CHAR>",
    "<EXEC_PROC_CONT_CHAR>",
    "\"(\"",
    "\")\"",
    "<EXEC_PROC_DELIMITER>",
    "<EXEC_PROC_CHAR>",
    "<SHELL_CONT_CHAR>",
    "<SHELL_CALL_DELIMITER>",
    "\"(\"",
    "\")\"",
    "<SHELL_CALL_CHAR>",
    "<OTHER_SQL_DELIMITER>",
    "<OTHER_SQL_CHAR>",
  };

}
