/* Generated By:JavaCC: Do not edit this line. SymbolParser.java */
package net.sourceforge.sqlunit.parsers;

import java.io.StringReader;
import java.util.Map;
import java.util.HashMap;

/**
 * Contains specifications and grammar for parsing Strings and replacing
 * embedded ant-style variables with values from the SymbolTable.
 * @author Sujit Pal (sujit.pal@cnet.com)
 * @version $Revision: 1.1 $
 */
public class SymbolParser implements SymbolParserConstants {

    private static StringBuffer resbuf;
    private static Map symbolMap;
    private static boolean partialOk = false;

    /**
     * This is the method that will be called from the client.
     * @param str the String with embedded ant-style variables.
     * @param syms a Map of symbols in the SymbolTable.
     * @param partialOk if true, exception will not be thrown if 
     * variable is not found, it is assumed that this will be passed
     * in later.
     * @throws ParseException if there was a problem parsing the String,
     * or if a variable could not be found in the SymbolTable.
     * @return a String with the variables replaced by their values.
     */
    public static String parse(String str, Map syms, boolean partialOk)
            throws ParseException {
        resbuf = new StringBuffer();
        StringReader reader = new StringReader(str);
        SymbolParser parser = new SymbolParser(reader);
        SymbolParser.symbolMap = syms;
        SymbolParser.partialOk = partialOk;
        parser.Substitute();
        return resbuf.toString();
    }

  final public void Substitute() throws ParseException {
    Token t;
    boolean inVar = false;
    StringBuffer varbuf = null;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case START_VAR:
      case CODE_CHAR:
      case END_VAR:
      case VAR_CHAR:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CODE_CHAR:
        jj_consume_token(CODE_CHAR);
          t = getToken(0);
          resbuf.append(t.image);
        break;
      case START_VAR:
        jj_consume_token(START_VAR);
          inVar = true;
          varbuf = new StringBuffer();
        break;
      case END_VAR:
        jj_consume_token(END_VAR);
          String var = varbuf.toString();
          String varValue =
              (String) SymbolParser.symbolMap.get("${" + var + "}");
          if (varValue == null) {
              if (SymbolParser.partialOk) {
                  varValue = "${" + var + "}";
              } else {
                  {if (true) throw new ParseException(
                      "Variable ${" + var + "} not defined in SymbolTable");}
              }
          }
          resbuf.append(varValue);
          inVar = false;
        break;
      case VAR_CHAR:
        jj_consume_token(VAR_CHAR);
          t = getToken(0);
          varbuf.append(t.image);
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 0:
      jj_consume_token(0);
      break;
    default:
      jj_la1[2] = jj_gen;
      ;
    }
  }

  public SymbolParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  public Token token, jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[3];
  static private int[] jj_la1_0;
  static {
      jj_la1_0();
   }
   private static void jj_la1_0() {
      jj_la1_0 = new int[] {0x1e,0x1e,0x1,};
   }

  public SymbolParser(java.io.InputStream stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new SymbolParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  public void ReInit(java.io.InputStream stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  public SymbolParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new SymbolParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  public SymbolParser(SymbolParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  public void ReInit(SymbolParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.Vector jj_expentries = new java.util.Vector();
  private int[] jj_expentry;
  private int jj_kind = -1;

  public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[5];
    for (int i = 0; i < 5; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 3; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 5; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  final public void enable_tracing() {
  }

  final public void disable_tracing() {
  }

}
