/* Generated By:JavaCC: Do not edit this line. SymbolParserConstants.java */
package net.sourceforge.sqlunit.parsers;

public interface SymbolParserConstants {

  int EOF = 0;
  int START_VAR = 1;
  int CODE_CHAR = 2;
  int END_VAR = 3;
  int VAR_CHAR = 4;

  int DEFAULT = 0;
  int IN_VAR = 1;

  String[] tokenImage = {
    "<EOF>",
    "\"${\"",
    "<CODE_CHAR>",
    "\"}\"",
    "<VAR_CHAR>",
  };

}
