# $Id: fixtext.sed,v 1.1 2004/10/14 01:57:37 spal Exp $
# $Source: /cvsroot/sqlunit/sqlunit/docs/fixtext.sed,v $
# Used to fix text file generated by jjdoc to be used as an included entity
# in the sqlunit-book.xml file. Replaces '<' and '>' symbols with the
# appropriate HTML entity.
#
s/</\&lt;/g
s/>/\&gt;/g
